- name: create aws instance connect
  hosts: localhost
  tasks:
    - name: Create an EC2 key
      ec2_key: name="mykey" region="eu-central-1"
      register: ec2_key
    - name: save private key
      copy: content="{{ ec2_key.key.private_key }}" dest=".ssh/id_rsa" mode=0600
      when: ec2_key.changed
    - name: create security group
      ec2_group:
        name: SSH-Allow
        description: SSH allow sg
        vpc_id: vpc-0d08f3b64c0ef84ec
        region: eu-central-1
        rules:
          - proto: tcp
            ports: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow SSH
- name: create aws instance
  hosts: localhost
  tasks:
    - name: create instanse
      ec2:
        key_name: "mykey"
        region: eu-central-1
        instance_type: t2.micro
        image: ami-05f7491af5eef733a
        wait: yes
        group: SSH-Allow
        count: 1
      register: created
    - name: update inventory
      add_host:
        name: "{{created.instances[0].public_ip}}"
        groups: aws-instans

- name: build boxfuse
  hosts: aws-instans
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Ensure package is present
      apt: name={{item}} state=present
      with_items:
        - git
        - default-jdk
        - maven
    - name: create directory
      file: path=/home/boxfuse state=directory
    - name: clone repository
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/boxfuse
    - name: build package
      shell: mvn package
      args:
        chdir: /home/boxfuse
    - name: PUT build to bucket
      aws_s3:
        bucket: mybacket1.dmitry-test.com
        object: hello-1.0.war
        src: /home/boxfuse/target/hello-1.0.war
        mode: put
